name: Deploy to SageMaker

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Pixi
      run: |
        curl -fsSL https://pixi.sh/install.sh | bash
        echo "$HOME/.pixi/bin" >> $GITHUB_PATH
    
    - name: Setup SSH for DTUWindGym
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.windenergy.dtu.dk >> ~/.ssh/known_hosts
    
    - name: Setup Environment
      run: |
        pixi install
        chmod +x scripts/setup_env.sh
        pixi run bash scripts/setup_env.sh
        
    - name: Configure AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
      run: |
        pixi run aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        pixi run aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        pixi run aws configure set default.region $AWS_DEFAULT_REGION

    - name: Build and Push Docker Image
      run: pixi run build-push

    - name: Start Training Job
      run: pixi run train
